### ISSUE TITLE
Actionbar is not correct shown, seems to be behind toolbar

### ISSUE THREAD

**Issue by jorgenstorlie** [Cheesebaron/SlidingMenuSharp#1]

**Comment by Cheesebaron** [comment]
Yes, I saw that. One of the few quirks it has right now. Definitely needs to be solved.

**Comment by gerryhigh** [comment]
Yeah, seeing it here as well with the latest source as of 5/2.

**Comment by adityam7** [comment]
Hey if you have an idea where the issue might be let me know so I can work on fixing it

**Comment by gerryhigh** [comment]
Given that Google is now telling people use their Navigation Drawer (http://developer.android.com/design/patterns/navigation-drawer.html) vs third party solutions I wonder if we should just bind to it?

**Comment by Cheesebaron** [comment]
You could as soon as Xamarin releases the new version of the Support package.

The issue with the overlap only occurs with the built in ActionBar, using thirdparty solutions like ActionBarSherlock and LegacyBar.

**Comment by Cheesebaron** [comment]
#7 should fix this :)
