### ISSUE TITLE
View.Measure failing on ArgumentException

### ISSUE THREAD

**Issue by rouen-sk** [Cheesebaron/SlidingMenuSharp#10]
When using SlidingMenuSharp, at random times my app crashes on the error below. I was not able to identify the reason - menu doesnt have to be manipulated or even open at the time of error.

05-22 16:30:30.340 I/MonoDroid(30088): UNHANDLED EXCEPTION: System.ArgumentException: 'jobject' must not be IntPtr.Zero.
05-22 16:30:30.340 I/MonoDroid(30088): Parameter name: jobject
05-22 16:30:30.340 I/MonoDroid(30088): at Android.Runtime.JNIEnv.CallVoidMethod (intptr,intptr,Android.Runtime.JValue[]) [0x00010] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.12-series/7f0e3d3c/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:499
05-22 16:30:30.340 I/MonoDroid(30088): at Android.Views.View.Measure (int,int) [0x0002d] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.12-series/7f0e3d3c/source/monodroid/src/Mono.Android/platforms/android-14/src/generated/Android.Views.View.cs:10375
05-22 16:30:30.340 I/MonoDroid(30088): at SlidingMenuSharp.CustomViewAbove.OnMeasure (int,int) [0x0002c] in d:\Devel\speedcamsprototype\Application\Android\SlidingMenuSharp\CustomViewAbove.cs:339
05-22 16:30:30.340 I/MonoDroid(30088): at Android.Views.View.n_OnMeasure_II (intptr,intptr,int,int) [0x00009] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.12-series/7f0e3d3c/source/monodroid/src/Mono.Android/platforms/android-14/src/generated/Android.Views.View.cs:11378
05-22 16:30:30.340 I/MonoDroid(30088): at (wrapper dynamic-method) object.bd42ef49-55d3-4861-a730-0897a6e73e12 (intptr,intptr,int,int) <IL 0x0001d, 0x0004b>
Unhandled Exception:

**Comment by rouen-sk** [comment]
OK, by trial and error process i found the reason. If you work with layouts in the activity which is using SlidingMenuSharp this way :

```
using (var mainlayout = FindViewById<RelativeLayout>(Resource.Id.mainLayout))
{
    mainLayout.SetBackgroundResource(Resource.Drawable.bg_blue);
}
```

you will get the exception in the question. However, if you dont use `using` (and i guess leave more time for some attached stuff to react, before GC dispose the reference?), everything works fine.

```
var mainlayout = FindViewById<RelativeLayout>(Resource.Id.mainLayout);
mainLayout.SetBackgroundResource(Resource.Drawable.bg_blue);
```

**Comment by Cheesebaron** [comment]
If you only use `mainlayout` to set the `BackgroundResource` why not just do:

```
FindViewById<RelativeLayout>(Resource.Id.mainLayout).SetBackgroundResource(Resource.Drawable.bg_blue);
```

Also where does this happen? Inside a Fragment or what?

**Comment by rouen-sk** [comment]
There are more commands using that layout, I just simpliefied it to show the difference. Code is inside an activity, app does not use fragments.

**Comment by Cheesebaron** [comment]
Alright, I suggest you look into refactoring your app to use them. Fragments are the bees knees! Anyways closing this issue :-)
