### ISSUE TITLE
Give me a hint

### ISSUE THREAD

**Issue by carlesls** [Cheesebaron/SlidingMenuSharp#11]
Wonderful SlidingMenuSharp...
But I would like to drag and drop even when the sliding content from the front has been slided away... give me a hint how to do it. Or how to replace one content when it is hidden. 
Thank you anyway.

**Comment by carlesls** [comment]
maybe this is too much to ask...

**Comment by Cheesebaron** [comment]
Not really relevant to the library, is it?
