### ISSUE TITLE
Get Slidng event and sliding position

### ISSUE THREAD

**Issue by SagarPanwala** [Cheesebaron/SlidingMenuSharp#12]
Is there any way we can get SlidingEvent and sliding position in our base activity or leftrightactivity. Please help me on this issues, I have done lot of googling related to this, But failed to achieve this.

**Comment by Cheesebaron** [comment]
What do you mean with "SlidingEvent"?

Can't you use any of these events: https://github.com/Cheesebaron/SlidingMenuSharp/blob/master/SlidingMenuSharp/CustomViewAbove.cs#L101-105 ?

**Comment by SagarPanwala** [comment]
Thanks . I want to know exact position of scroll. How can I know that?
You mean to say I have to used PageScrollState Event, right ? How to use that?

**Comment by Cheesebaron** [comment]
Use the `PageScrolled` event https://github.com/Cheesebaron/SlidingMenuSharp/blob/master/SlidingMenuSharp/SlidingMenuEventArgs.cs#L26-30 You have all you need in there. I actually don't think the `PageScrollState` event is wired up.

How to use it? Subscribe to it!
