### ISSUE TITLE
there are two id with same name content_frame in the layouts

### ISSUE THREAD

**Issue by carlesls** [Cheesebaron/SlidingMenuSharp#13]
One inside content_frame and another inside responsive_content_frame.
This could led to error if you seek them via Resource.Id.content_frame, doesn't it?
Am I correct? do I miss something?
Goodbye.

**Comment by Cheesebaron** [comment]
Dunno what you are referring to... Elaborate please.

**Comment by carlesls** [comment]
How do you differentiate between Resource.Id.content_frame and another Resource.Id.content_frame (same android:id attribute name) when they come from different Layouts' id? Do I miss something here? is that correct?
Excuse my English.

**Comment by Cheesebaron** [comment]
Why would you need to do that? They are two different layouts. You can reuse ID's for your layouts. They are just there to be able to get a specific element from an ID, nothing else. I don't see a problem here. If you believe that there is a problem with reusing ID"s please be more specific and point out exactly where this problem occurs.

**Comment by carlesls** [comment]
Ok... imagine you inflate two FrameLayouts with the same parent id (attribute) in one OnCreate(...) for two MockView (Custom views)... wouldn't this create any problem at all?

**Comment by Cheesebaron** [comment]
So you want to do something like this:

```
var layout1 = inflater.Inflate(Resource.Layout.derp);
var layout2 = inflater.Inflate(Resource.Layout.derp);
```

Why would this matter if they each use the same ID inside? When you fetch a view inside you do it on the reference you have to the inflated layout.

However, if you do something like this:

```
<TextView
  android:id="@+id/derp"
  .. />
<TextView
  android:id="@+id/derp"
  .. />
```

In the same layout, you will encounter issues. Yes.

If this is not what you are describing. Be more specific!

**Comment by carlesls** [comment]
myfirstview = inflater.Inflate(Resource.Layout.SameLayout);
mysecondview = inflater.Inflate(Resource.Layout.SameLayout);
Layout l1 = myfirstview.FindById<Layout>(Resource.Id.parentlayout)
Layout l2 = mysecondview.FindById<Layout>(Resource.Id.parentlayout)

forget it... I concede... 
I do not know why but in some cases this the same id leads to error... that's my humble guess.

**Comment by Cheesebaron** [comment]
No it doesn't.
