### ISSUE TITLE
Exception while restoring activity state : Parcel android.os.Parcel@42ab6ad8: Unmarshalling unknown type code 7209057 at offset 1064

### ISSUE THREAD

**Issue by admiralnico** [Cheesebaron/SlidingMenuSharp#14]
Can reproduce this error by: 

 If you use dev tools on a device and enable the 'Don't Keep
Activities' option you can easily reproduce by pressing home from an
activity that has the Sliding Menu, and then switching back to the app
again.

**Comment by Cheesebaron** [comment]
Fixed in #15?

**Comment by admiralnico** [comment]
Yes fixed in #15 :)
