### ISSUE TITLE
tried to execute code in unprepared class 'Landroid/content/res/XResources$XTypedArray;' (3)

### ISSUE THREAD

**Issue by karimjouini** [Cheesebaron/SlidingMenuSharp#17]
Hello,

I am facing this issue (described in this link: http://forum.xda-developers.com/showpost.php?p=52733303&postcount=11445 )

I face it only on some phones (Samsung Galaxy S5 mini for instance)

Did anyone see this?

Thanks,
Karim

**Comment by Cheesebaron** [comment]
Do you have a stack trace?

**Comment by karimjouini** [comment]
The exact same one on the link I posted :)

It is happening in the SetContentView

---

De : Tomasz Cieleckimailto:notifications@github.com
Envoyé : ‎08/‎06/‎2015 13:20
À : Cheesebaron/SlidingMenuSharpmailto:SlidingMenuSharp@noreply.github.com
Cc : Karim Jouinimailto:karim.jouini@pepinotech.com
Objet : Re: [SlidingMenuSharp] tried to execute code in unprepared class 'Landroid/content/res/XResources$XTypedArray;' (3) (#17)

Do you have a stack trace?

**Comment by Cheesebaron** [comment]
What are you using XPosed framework for?

**Comment by karimjouini** [comment]
I am not aware I am using it :) I am using Xamarin Android with ur lib

Here my own stack trace

/dalvikvm(11579): ERROR: tried to execute code in unprepared class 'Landroid/content/res/XResources$XTypedArray;' (3)

I/dalvikvm(11579): "main" prio=5 tid=1 RUNNABLE

I/dalvikvm(11579):   | group="main" sCount=0 dsCount=0 obj=0x41826ea0 self=0x41813008

I/dalvikvm(11579):   | sysTid=11579 nice=-11 sched=0/0 cgrp=apps handle=1074266452

I/dalvikvm(11579):   | state=R schedstat=( 0 0 0 ) utm=150 stm=30 core=1

I/dalvikvm(11579):   at android.content.res.XResources$XTypedArray.getInt(XResources.java:-1)

I/dalvikvm(11579):   at mono.android.TypeManager.n_activate(Native Method)

I/dalvikvm(11579):   at mono.android.TypeManager.Activate(TypeManager.java:7)

I/dalvikvm(11579):   at slidingmenusharp.SlidingMenu.<init>(SlidingMenu.java:24)

I/dalvikvm(11579):   at java.lang.reflect.Constructor.constructNative(Native Method)

I/dalvikvm(11579):   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

I/dalvikvm(11579):   at android.view.LayoutInflater.createView(LayoutInflater.java:600)

I/dalvikvm(11579):   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)

I/dalvikvm(11579):   at android.view.LayoutInflater.inflate(LayoutInflater.java:470)

I/dalvikvm(11579):   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

I/dalvikvm(11579):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631

---

De : Tomasz Cieleckimailto:notifications@github.com
Envoyé : ‎08/‎06/‎2015 13:22
À : Cheesebaron/SlidingMenuSharpmailto:SlidingMenuSharp@noreply.github.com
Cc : Karim Jouinimailto:karim.jouini@pepinotech.com
Objet : Re: [SlidingMenuSharp] tried to execute code in unprepared class 'Landroid/content/res/XResources$XTypedArray;' (3) (#17)

What are you using XPosed framework for?

**Comment by karimjouini** [comment]
Seems it got truncated

Pasting again

06-08 16:47:35.468 E/dalvikvm(11051): ERROR: tried to execute code in unprepared class 'Landroid/content/res/XResources$XTypedArray;' (3)
06-08 16:47:35.468 I/dalvikvm(11051): "main" prio=5 tid=1 RUNNABLE
In mgmain JNI_OnLoad
06-08 16:47:35.468 I/dalvikvm(11051):   | group="main" sCount=0 dsCount=0 obj=0x41826ea0 self=0x41813008
06-08 16:47:35.468 I/dalvikvm(11051):   | sysTid=11051 nice=-11 sched=0/0 cgrp=apps handle=1074266452
06-08 16:47:35.468 I/dalvikvm(11051):   | state=R schedstat=( 0 0 0 ) utm=182 stm=61 core=1
06-08 16:47:35.478 I/dalvikvm(11051):   at android.content.res.XResources$XTypedArray.getInt(XResources.java:-1)
06-08 16:47:35.478 I/dalvikvm(11051):   at mono.android.TypeManager.n_activate(Native Method)
06-08 16:47:35.478 I/dalvikvm(11051):   at mono.android.TypeManager.Activate(TypeManager.java:7)
06-08 16:47:35.478 I/dalvikvm(11051):   at md503d45fbbf34f4dfcd729d358f6c4ced1.SlidingMenu.<init>(SlidingMenu.java:32)
06-08 16:47:35.478 I/dalvikvm(11051):   at java.lang.reflect.Constructor.constructNative(Native Method)
06-08 16:47:35.478 I/dalvikvm(11051):   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
06-08 16:47:35.478 I/dalvikvm(11051):   at android.view.LayoutInflater.createView(LayoutInflater.java:600)
06-08 16:47:35.478 I/dalvikvm(11051):   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
06-08 16:47:35.478 I/dalvikvm(11051):   at android.view.LayoutInflater.inflate(LayoutInflater.java:470)
06-08 16:47:35.478 I/dalvikvm(11051):   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
06-08 16:47:35.478 I/dalvikvm(11051):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
06-08 16:47:35.478 I/dalvikvm(11051):   at android.view.LayoutInflater.inflate(Native Method)
06-08 16:47:35.478 I/dalvikvm(11051):   at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
06-08 16:47:35.478 I/dalvikvm(11051):   at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
06-08 16:47:35.478 I/dalvikvm(11051):   at md560df7c94049232d58e0a099c07de37f9.SlidingMenuActivity.n_onCreate(Native Method)
06-08 16:47:35.478 I/dalvikvm(11051):   at md560df7c94049232d58e0a099c07de37f9.SlidingMenuActivity.onCreate(SlidingMenuActivity.java:40)
06-08 16:47:35.478 I/dalvikvm(11051):   at android.app.Activity.performCreate(Activity.java:5541)
06-08 16:47:35.478 I/dalvikvm(11051):   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
06-08 16:47:35.478 I/dalvikvm(11051):   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
06-08 16:47:35.488 I/dalvikvm(11051):   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
06-08 16:47:35.488 I/dalvikvm(11051):   at android.app.ActivityThread.access$900(ActivityThread.java:172)
06-08 16:47:35.488 I/dalvikvm(11051):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
06-08 16:47:35.488 I/dalvikvm(11051):   at android.os.Handler.dispatchMessage(Handler.java:102)
06-08 16:47:35.488 I/dalvikvm(11051):   at android.os.Looper.loop(Looper.java:146)
06-08 16:47:35.488 I/dalvikvm(11051):   at android.app.ActivityThread.main(ActivityThread.java:5694)
06-08 16:47:35.488 I/dalvikvm(11051):   at java.lang.reflect.Method.invokeNative(Native Method)
06-08 16:47:35.488 I/dalvikvm(11051):   at java.lang.reflect.Method.invoke(Method.java:515)
06-08 16:47:35.488 I/dalvikvm(11051):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
06-08 16:47:35.488 I/dalvikvm(11051):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
06-08 16:47:35.488 I/dalvikvm(11051):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
06-08 16:47:35.488 I/dalvikvm(11051):   at dalvik.system.NativeStart.main(Native Method)

**Comment by Cheesebaron** [comment]
I can't be responsible for a bug that is caused by Xposed. Find a rom which does not use it.

**Comment by karimjouini** [comment]
Thank you Cheesebaron

This is reported by a Customer, so we are trying to find a workaround
Honestly I have no idea how Xposed is interacting with this. If you have any pointer I could use ... :) Would be super helpful!

**Comment by Cheesebaron** [comment]
Workaround is to not use Xposed. As you see in the stack trace, it does something in the inflation process, which is out of my control.

**Comment by karimjouini** [comment]
Thank you for your help @Cheesebaron :) I am basically asking for advice, and you are answering "not my fault"

I completly understand it is not your "fault", was looking for any avise there or any idea I could proceed with

I filed an issue on XPosed, to seek any workaround they could think of.

**Comment by Cheesebaron** [comment]
You should not trust any users using Xposed anyways.
