### ISSUE TITLE
Slide menu doesn't fill

### ISSUE THREAD

**Issue by david99999** [Cheesebaron/SlidingMenuSharp#3]
Hi, the items of the slide menu doesn't display correctly when the slide is set to left mode
![Screenshot_2013-04-24-14-40-10 1 ](https://f.cloud.github.com/assets/4248801/421909/d70ada6a-ad15-11e2-892a-6773d403b714.png)
It loks like floating on the right of the menu

**Comment by Cheesebaron** [comment]
If you go to the SlidingMenu Properties Activity and set Scroll Scale all the way to the right, does it look fine in that activity?

**Comment by david99999** [comment]
jejeje, my fault for not testing that, you are right, all the scroll scale to the right is the way
by the way, what means scroll scale? whats the purpose?

**Comment by Cheesebaron** [comment]
Fixed!
