### ISSUE TITLE
Black Slide using google maps api v2

### ISSUE THREAD

**Issue by david99999** [Cheesebaron/SlidingMenuSharp#4]
Hi, I'm using together the legacybar and slidingmenusharp, when perform the sliding appears a black section in the slide content, I've tried to make a snapshot but doesn't catch the black section it appears like it were working ok.

the content of the view (SlidingFragmentActivity) is a FrameLayout whitin a linearlayout, and the content of the slidemenu is a linearlayout, 

other thing, how can i use SetSlidingActionBarEnabled(false); whitn legacybar, I put that line in OnCreate, but still sliding the legacybar

I'm using the google maps api v2 and the map is showing correctly

**Comment by Cheesebaron** [comment]
Best would be if you made a reproducible sample.

As for the LegacyBar, you can't make it not slide right now.

**Comment by david99999** [comment]
Hi, [here](https://www.dropbox.com/s/pqlw0pstqpvmmpe/Example.rar) is the example, can you plase check it out?

**Comment by Cheesebaron** [comment]
![device-2013-05-10-223123](https://f.cloud.github.com/assets/249719/490113/9c9308ce-b9b0-11e2-8f8b-8d5d964b409a.png)

Doesn't seem black to me? I don't really understand your issue.
