### ISSUE TITLE
Left and Right menu Shadows aren't appearing correctly

### ISSUE THREAD

**Issue by Redth** [Cheesebaron/SlidingMenuSharp#5]
See the video here: http://www.screencast.com/t/fhEonxZJ7gN

The shadow on the left menu doesn't show at all, and the shadow on the right shows incorrectly...  This occurs in the Sample app on 4.2 emulator, as well as in my own app.

**Comment by Cheesebaron** [comment]
Thanks @Redth! Fixed now!
