### ISSUE TITLE
TouchModeAbove & TouchModeBehind Possible Issue

### ISSUE THREAD

**Issue by CodeMonkeyThe2nd** [Cheesebaron/SlidingMenuSharp#9]
I have set these two properties like so:

SlidingMenu.TouchModeAbove = TouchMode.Margin;
SlidingMenu.TouchModeBehind = TouchMode.Margin;

But I am still able to slide the menu in from the right hand edge of the screen. This means I am having to disable all Sliding when using a ViewPager else the user opens the slider when they try swipe right.

Any ideas why this might be?

PS: Thanks for the awesome control!

**Comment by Cheesebaron** [comment]
I don't really see the issue here. If you do not want to have the menu appear when you are swiping from the right use `TouchMode.None`. SlidingMenuSharp is a direct port from jfeinstein's popular SlidingMenu, so if you are in doubt, look through his docs, most of it applies here as well.

I agree that you don't want the SlidingMenu appear when swiping from right, as SlidingMenu and ViewPager are two UI controls which use the same gesture for navigation. What does the user expect when swiping from either side? I would personally not want to have them both appearing :)

**Comment by CodeMonkeyThe2nd** [comment]
But why is there the option for TouchMode.Margin, does it have any effect when setting the TouchMode to this?

The slide gesture also becomes a problem when using a map, when the user tries to pan the map left they regularly open the slider. Does this mean on every fragment that has to be able to swipe left I have to completely disable the swipe gesture for the slider?

**Comment by Cheesebaron** [comment]
`TouchMode.Margin` does exactly what it says. Triggers the SlidingMenu when you swipe near the edge of the screen. Approximately 48px on both sides.

It is entirely up to you how the UX is in your app. SlidingMenu uses the right and left swipe gesture to trigger it, but can also be triggered with buttons etc. If you choose to use it along with other controls that implement same type of gestures, like ViewPager; Maps; Gallery; etc., then it is up to you to find another way to trigger either of them. Do what you feel is the best thing to do.

**Comment by CodeMonkeyThe2nd** [comment]
Well then i still think TouchMode.Margin isn't being set correctly. I have TouchMode set to Margin but I can still pull the slider open from anywhere on the screen. 

It's not really a big issue, I've just disabled TouchMode on screens which need the gesture, but I do think TouchMode.Margin; is not having any affect on where the slider can be pulled out from.

**Comment by Cheesebaron** [comment]
I tested this yesterday and it does seem to have an effect here. If you can give me some code where I can reproduce your issue, it will be a lot easier for me to find out if your postulate is actually true.

**Comment by CodeMonkeyThe2nd** [comment]
I have tested this with the Sample project provided with the component, in BaseActivity I updated

SlidingMenu.TouchModeAbove = TouchMode.Fullscreen;

to 

SlidingMenu.TouchModeAbove = TouchMode.Margin;

but using an HTC One and a Galaxy SII I can still pull the slider out from the middle of the screen.

**Comment by Cheesebaron** [comment]
As `BaseActivity` indicates it is used as a base for others. So `TouchModeAbove` might get set to something else in that Activity. Please make sure what exactly it is.

**Comment by CodeMonkeyThe2nd** [comment]
Apologies Cheesebaron! I just realised I was setting this in my child activities as well, i've been half asleep this week.
